version: '3'

volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_traefik: {}
  production_django_media: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile

    image: restaurant_production_django
    volumes:
      - production_django_media:/app/restaurant/media
    depends_on:
      - postgres
      - redis
    environment:
      DJANGO_READ_DOT_ENV_FILE: ${DJANGO_READ_DOT_ENV_FILE}
      DJANGO_SETTINGS_MODULE: ${DJANGO_SETTINGS_MODULE}
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DJANGO_ADMIN_URL: ${DJANGO_ADMIN_URL}
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}
      DJANGO_SECURE_SSL_REDIRECT: ${DJANGO_SECURE_SSL_REDIRECT}
      DJANGO_ACCOUNT_ALLOW_REGISTRATION: ${DJANGO_ACCOUNT_ALLOW_REGISTRATION}
      WEB_CONCURRENCY: ${WEB_CONCURRENCY}
      CELERY_FLOWER_USER: ${CELERY_FLOWER_USER}
      CELERY_FLOWER_PASSWORD: ${CELERY_FLOWER_PASSWORD}
      REDIS_URL: ${REDIS_URL}
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: restaurant_production_postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - production_postgres_data_backups:/backups
    env_file:
      - ./.envs/.production/.postgres

  traefik:
    build:
      context: .
      dockerfile: ./compose/production/traefik/Dockerfile
    image: restaurant_production_traefik
    depends_on:
      - django
    volumes:
      - production_traefik:/etc/traefik/acme
    ports:
      - '0.0.0.0:80:80'
      - '0.0.0.0:443:443'
      - '0.0.0.0:5555:5555'

  redis:
    image: docker.io/redis:6

  celeryworker:
    <<: *django
    image: restaurant_production_celeryworker
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: restaurant_production_celerybeat
    command: /start-celerybeat

  flower:
    <<: *django
    image: restaurant_production_flower
    command: /start-flower

  nginx:
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
    image: restaurant_local_nginx
    depends_on:
      - django
    volumes:
      - production_django_media:/usr/share/nginx/media:ro
