# Generated by Django 4.2.9 on 2024-02-03 15:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("positions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="url",
            field=models.CharField(default="/", max_length=100),
        ),
    ]
