# Generated by Django 4.2.9 on 2024-02-03 16:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("positions", "0002_alter_category_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="priority",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="position",
            name="priority",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="subcategory",
            name="priority",
            field=models.IntegerField(default=0),
        ),
    ]
