# Generated by Django 4.2.9 on 2024-02-03 16:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("positions", "0003_category_priority_position_priority_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="position",
            name="cooking_time",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="position",
            name="description",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="position",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="positions/"),
        ),
        migrations.AddField(
            model_name="position",
            name="is_new",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="position",
            name="price",
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=100),
        ),
        migrations.AddField(
            model_name="position",
            name="spiciness",
            field=models.CharField(
                choices=[
                    ("MILD", "Не острая"),
                    ("LOW", "Незначительно"),
                    ("MEDIUM", "Средне"),
                    ("HOT", "Острое"),
                    ("EXTRA_HOT", "Очень острое"),
                ],
                default="MILD",
                max_length=20,
                verbose_name="Острота",
            ),
        ),
        migrations.AddField(
            model_name="position",
            name="weight",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
