# Generated by Django 4.2.9 on 2024-02-03 16:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("positions", "0004_position_cooking_time_position_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="position",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default="100.0", max_digits=100
            ),
        ),
    ]
