# Generated by Django 4.2.9 on 2024-02-03 16:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("positions", "0006_alter_position_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="position",
            name="description",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
