# Generated by Django 4.2.9 on 2024-02-07 10:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("positions", "0007_alter_position_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="position",
            name="price",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
