# Generated by Django 4.2.9 on 2024-02-11 22:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("positions", "0009_position_is_liquid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="position",
            name="is_liquid",
        ),
        migrations.AddField(
            model_name="position",
            name="measurement",
            field=models.CharField(
                choices=[
                    ("GRAM", "гр"),
                    ("KILOGRAM", "КГ"),
                    ("LITER", "L"),
                    ("MILLILITER", "ml"),
                ],
                default="GRAM",
                max_length=20,
                verbose_name="Измерение",
            ),
        ),
    ]
