# Generated by Django 4.2.9 on 2024-02-11 22:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("positions", "0010_remove_position_is_liquid_position_measurement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="position",
            name="weight",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
