# Generated by Django 4.2.9 on 2024-02-11 22:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("positions", "0011_alter_position_weight"),
    ]

    operations = [
        migrations.AlterField(
            model_name="position",
            name="measurement",
            field=models.CharField(
                choices=[("гр", "гр"), ("КГ", "КГ"), ("L", "L"), ("ml", "ml")],
                default="гр",
                max_length=20,
                verbose_name="Измерение",
            ),
        ),
        migrations.AlterField(
            model_name="position",
            name="spiciness",
            field=models.CharField(
                choices=[
                    ("Не острая", "Не острая"),
                    ("Незначительно", "Незначительно"),
                    ("Средне", "Средне"),
                    ("Острое", "Острое"),
                    ("Очень острое", "Очень острое"),
                ],
                default="MILD",
                max_length=20,
                verbose_name="Острота",
            ),
        ),
    ]
