# Generated by Django 4.2.9 on 2024-02-11 23:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("positions", "0013_alter_position_measurement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="position",
            name="price",
            field=models.CharField(default="0"),
        ),
        migrations.AlterField(
            model_name="position",
            name="weight",
            field=models.CharField(default="0"),
        ),
    ]
