# Generated by Django 4.2.9 on 2024-02-12 22:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("positions", "0016_alter_category_options_alter_position_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="position",
            name="spiciness",
            field=models.CharField(
                choices=[
                    ("Не острая", "Не острая"),
                    ("Незначительно", "Незначительно"),
                    ("Средне", "Средне"),
                    ("Острое", "Острое"),
                    ("Очень острое", "Очень острое"),
                ],
                default="Не острая",
                max_length=20,
                verbose_name="Острота",
            ),
        ),
    ]
