# Generated by Django 4.2.9 on 2024-02-28 18:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("positions", "0020_position_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tip",
            name="card_number",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="Номер карты"
            ),
        ),
    ]
